services:
    api-gateway:
      build:
        context: services/ts
        dockerfile: api-gateway/Dockerfile
      image: $DOCKER_HUB_USERNAME/finus-api-gateway:$RELEASE_VERSION
      env_file: 
      - path: ./default_container.env
      environment:
        - NODE_ENV=development
      ports:
        - "3000:8000"
      depends_on:
        - auth
        - user
        - analytics
        - market
  
    auth:
      build: 
        context: services/ts
        dockerfile: auth/Dockerfile
      image: $DOCKER_HUB_USERNAME/finus-auth:$RELEASE_VERSION
      env_file: 
      - path: ./default_container.env
      environment: 
        - DB_PASSWORD

        
    user:
      build:
        context: services/ts
        dockerfile: user/Dockerfile
      image: $DOCKER_HUB_USERNAME/finus-user:$RELEASE_VERSION
      env_file: 
      - path: ./default_container.env
      environment: 
        - DB_PASSWORD
    
    analytics:
      build:
        context: services/python/analytics
        dockerfile: Dockerfile
      image: $DOCKER_HUB_USERNAME/finus-analytics:$RELEASE_VERSION
      env_file: 
      - path: ./default_container.env
      environment: 
      - DB_PASSWORD
      
    market:
      build: 
        context: services/python/market
        dockerfile: Dockerfile
      image: $DOCKER_HUB_USERNAME/finus-market:$RELEASE_VERSION
      env_file: 
      - path: ./default_container.env
  
    #connect manually with `mysql -h 127.0.0.1 -P 3306 -u root -p`
    database:
      image: mysql:8.0-debian
      volumes: 
      - db_data:/var/lib/mysql
      - ./services/database:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=$(DB_ROOT_PASSWORD)
        - MYSQL_PASSWORD=$(DB_PASSWORD)
      ports:
        - "3306:3306"

volumes: 
  db_data: 
