FROM oven/bun:1.3.9-slim

WORKDIR /app

COPY package.json bun.lockb ./
RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install

COPY tsconfig.* .
COPY vite.config.ts .
COPY index.* .
COPY public ./public
COPY src ./src

ENTRYPOINT [ "/bin/bash", "-c", "exit" ]
