services:
  webserver-base:
    image: finus-webserver-base:local
    build:
      dockerfile: Dockerfile.base

  user-input:
    build:
      dockerfile: Dockerfile.test
    depends_on:
      - webserver-base

  mutation-tests:
    build:
      dockerfile: Dockerfile.mutation.test
    depends_on:
      - webserver-base
