services:
  webserver-base:
    image: $DOCKER_HUB_USERNAME/finus-webserver-base:$RELEASE_VERSION
    build:
      dockerfile: Dockerfile.base

  webserver:
    image: $DOCKER_HUB_USERNAME/finus-webserver:$RELEASE_VERSION
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webserver-base
