FROM finus-webserver-base:local AS bun-base

WORKDIR /app

COPY stryker.conf.json .
COPY test .

#SUPRISE! Stryker needs node to run.
FROM node:20

WORKDIR /app

# Copy everything (including node_modules) from Bun stage
COPY --from=bun-base /app /app

# Run Stryker with Node
ENTRYPOINT ["npx", "stryker", "run"]
