on:
  workflow_call:
    inputs:
      dockerfile-dir:
        type: string
        required: true
      DOCKER_HUB_USERNAME:
        type: string
        required: true

    secrets:
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  publish-compose:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.dockerfile-dir }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: docker/setup-buildx-action@000d75d273dec231f74115df50b6ee04c9b25e55
      - uses: docker/login-action@0d33dcdeedfe8f116d005eaa548b93b404f61fa8
        with: 
          username: ${{ inputs.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: | 
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          RELEASE_VERSION=$(echo $BRANCH_NAME | sed "s|release\/||g")

          echo RELEASE_VERSION=$RELEASE_VERSION         >  .env
          echo DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME >> .env

          echo "Building images..."
          docker compose build
          echo "Pushing images..."
          docker compose push

          echo RELEASE_VERSION=latest                   >  .env
          echo DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME >> .env
          echo "Re-building with lastest tag..."
          docker compose build
          echo "Pushing images..."
          docker compose push

        env:
          DOCKER_HUB_USERNAME: ${{ inputs.DOCKER_HUB_USERNAME }}

