name: publishBackendImages

on:
  push:
    branches: [ "release/**" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: setup
      run: |
        cd app/server
        rm .env
        BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        RELEASE_VERSION=echo $BRANCH_NAME | sed "s|release\/||g"
    - name: build
      run: docker compose build
    - name: publish
      run: docker compose push
