on:
  workflow_call:
    inputs:
      docker_hub_username:
        type: string
        required: true
      release_version:
        type: string
        required: true
      dockerfile_dir:
        type: string
        required: true
    secrets:
      docker_hub_password:
        type: string
        required: true
        

jobs:
  publish_compose:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: app/server
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: docker/setup-buildx-action@000d75d273dec231f74115df50b6ee04c9b25e55
      - uses: docker/login-action@0d33dcdeedfe8f116d005eaa548b93b404f61fa8
        with: 
          username: ${{ vars.docker_hub_username }}
          password: ${{ secrets.docker_hub_password  }}
        run: | 
          echo RELEASE_VERSION=${{ vars.release_version }}          >  .env
          echo DOCKER_HUB_USERNAME=${{ vars.docker_hub_username }}  >> .env

          echo "Building images..."
          docker compose build -q
          echo "Pushing images..."
          docker compose push  -q

