name: "Publish Backend Images"

on:
  push:
    branches: [ "release/**" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-images:
    runs-on: ubuntu-24.04
    environment: "Docker hub"
    uses: ./.github/workflows/docker_compose_publish.yml
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      dockerfile-dir: app/server
    secrets: inherit

#      - uses: ./.github/workflows/docker_compose_publish.yml
#        with: 
#         docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
#         release-version: 0
#         dockerfile-dir: app/client
